Repository Newyork-Squad/MovieApp, pull requests merged in 2025-09, with the labels that each got.

#15 Refactor: Splash screen
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: Refactor

#17 Refactor: Error UI
  app/src/main/res/layout/error2.xml
  app/src/main/res/layout/error_movie_details.xml
  app/src/main/res/layout/error_search.xml
  app/src/main/res/layout/error_tv_show_details.xml
  app/src/main/res/layout/fragment_actor_details.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_exploring.xml
  app/src/main/res/layout/fragment_list_details.xml
  app/src/main/res/layout/fragment_my_lists.xml
  app/src/main/res/layout/fragment_my_ratings.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_load_state.xml
  app/src/main/res/raw-night/lost_internet_animation.json
  app/src/main/res/raw/lost_internet_animation.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_actor_details_scene.xml
  app/src/main/res/xml/fragment_exploring_scene.xml
Labels: Refactor

#29 Feature: Onboarding flow
  app/src/main/java/com/karrar/movieapp/data/local/AppConfiguration.kt
  app/src/main/java/com/karrar/movieapp/data/local/SharedPreferences.kt
  app/src/main/java/com/karrar/movieapp/di/DataBaseModule.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/startUp/GetStartUpStateUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/startUp/MarkAsNotFirstLaunchUseCase.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnboardingContent.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnboardingFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/adapter/OnboardingContentAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/adapter/OnboardingImageAdapter.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/drawable-hdpi/onboarding_first_image.webp
  app/src/main/res/drawable-hdpi/onboarding_second_image.webp
  app/src/main/res/drawable-hdpi/onboarding_third_image.webp
  app/src/main/res/drawable-mdpi/onboarding_first_image.webp
  app/src/main/res/drawable-mdpi/onboarding_second_image.webp
  app/src/main/res/drawable-mdpi/onboarding_third_image.webp
  app/src/main/res/drawable-xhdpi/onboarding_first_image.webp
  app/src/main/res/drawable-xhdpi/onboarding_second_image.webp
  app/src/main/res/drawable-xhdpi/onboarding_third_image.webp
  app/src/main/res/drawable-xxhdpi/onboarding_first_image.webp
  app/src/main/res/drawable-xxhdpi/onboarding_second_image.webp
  app/src/main/res/drawable-xxhdpi/onboarding_third_image.webp
  app/src/main/res/drawable/rounded_blue_button_shape.xml
  app/src/main/res/drawable/rounded_white_button_shape.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/item_onboarding_content_messages.xml
  app/src/main/res/layout/item_onboarding_image_page.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#25 Refactor/login screen
  app/build.gradle
  app/src/main/java/com/karrar/movieapp/data/local/AppConfiguration.kt
  app/src/main/java/com/karrar/movieapp/data/local/DataStorePreferences.kt
  app/src/main/java/com/karrar/movieapp/data/remote/response/login/GuestSessionResponse.kt
  app/src/main/java/com/karrar/movieapp/data/remote/service/MovieService.kt
  app/src/main/java/com/karrar/movieapp/data/repository/AccountRepository.kt
  app/src/main/java/com/karrar/movieapp/data/repository/AccountRepositoryImp.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/login/LoginAsGuestUseCase.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginViewModel.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/color/button_login_background.xml
  app/src/main/res/color/login_button_text_color.xml
  app/src/main/res/color/text_input_stroke_colors.xml
  app/src/main/res/drawable/bg_dialog.xml
  app/src/main/res/drawable/bg_divider.xml
  app/src/main/res/drawable/cine_verse_logo.png
  app/src/main/res/drawable/custom_cursor.xml
  app/src/main/res/drawable/ic_signup.png
  app/src/main/res/layout/dialog_signup.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Refactor

#63 Feature/search
  app/src/main/java/com/karrar/movieapp/data/local/database/MovieDataBase.kt
  app/src/main/java/com/karrar/movieapp/di/DataBaseModule.kt
  app/src/main/java/com/karrar/movieapp/ui/search/SearchFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/search/SearchViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/search/adapters/MediaSearchAdapter.kt
  app/src/main/res/drawable/bg_card_rounded.xml
  app/src/main/res/drawable/bg_icon_circle.xml
  app/src/main/res/drawable/color_cursor.xml
  app/src/main/res/drawable/ic_no_search_results.xml
  app/src/main/res/layout/fragment_all_movie.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_actor_search.xml
  app/src/main/res/layout/item_history_header.xml
  app/src/main/res/layout/item_media_search.xml
  app/src/main/res/layout/item_media_search_grid.xml
  app/src/main/res/layout/item_media_search_list.xml
  app/src/main/res/layout/item_search_history.xml
  app/src/main/res/layout/no_search_results.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, Refactor

#54 Feature: Match question screen
  app/build.gradle
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchScreenFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/Choice.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestion.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestionInteractionListener.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestionUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestionsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestionsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/adapter/ChoicesAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/adapter/MatchAdapter.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/drawable/nav_icon_home.xml
  app/src/main/res/drawable/nav_icon_magic_stick.xml
  app/src/main/res/drawable/nav_icon_search.xml
  app/src/main/res/drawable/nav_icon_user_square.xml
  app/src/main/res/layout/fragment_match_questions.xml
  app/src/main/res/layout/fragment_match_screen.xml
  app/src/main/res/layout/item_match_choice.xml
  app/src/main/res/layout/item_match_question.xml
  app/src/main/res/layout/item_wrap_match_choice.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#62 collection-bottom-sheet
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/MovieDetailsUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/MovieDetailsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/movieDetailsUIState/MovieUIState.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/saveMovie/SaveListAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/saveMovie/SaveMovieDialog.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/saveMovie/SaveMovieViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/saveMovie/uiState/SaveMovieUIEvent.kt
  app/src/main/res/drawable/bottom_sheet_corners.xml
  app/src/main/res/drawable/cancel.xml
  app/src/main/res/drawable/line_1.xml
  app/src/main/res/layout/dialog_save_movie.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Refactor

#70 refactor/adjust-home-sections
  app/src/main/java/com/karrar/movieapp/domain/enums/AllMediaType.kt
  app/src/main/java/com/karrar/movieapp/domain/enums/HomeItemsType.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/allMedia/CheckIfMediaIsSeriesUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/allMedia/GetMediaByTypeUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/home/HomeUseCasesContainer.kt
  app/src/main/java/com/karrar/movieapp/ui/allMedia/AllMovieFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeItem.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/home/adapter/HomeAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/home/homeUiState/HomeUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/CreatedListAdapter.kt
  app/src/main/res/layout/item_needmoretowatch.xml
  app/src/main/res/layout/item_whatshouldwatch.xml
  app/src/main/res/layout/list_airing_today.xml
  app/src/main/res/layout/list_home_collections.xml
  app/src/main/res/layout/list_recently_viewed.xml
  app/src/main/res/layout/list_tv_shows.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#78 Bugfix/search history
  app/src/main/java/com/karrar/movieapp/data/local/database/daos/MovieDao.kt
  app/src/main/java/com/karrar/movieapp/data/local/database/entity/SearchHistoryEntity.kt
  app/src/main/java/com/karrar/movieapp/data/repository/MovieRepository.kt
  app/src/main/java/com/karrar/movieapp/data/repository/MovieRepositoryImp.kt
  app/src/main/java/com/karrar/movieapp/domain/mappers/search/SearchHistoryItemMapper.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/searchUseCase/ClearSearchHistoryUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/searchUseCase/DeleteSearchHistoryItemUseCase.kt
  app/src/main/java/com/karrar/movieapp/ui/search/SearchViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/search/adapters/SearchHistoryAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/search/mediaSearchUIState/SearchHistoryUIState.kt
  app/src/main/java/com/karrar/movieapp/ui/search/uiStatMapper/SearchHistoryUIStateMapper.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_history_header.xml
  app/src/main/res/layout/item_search_history.xml
Labels: bug, enhancement, Refactor

#102 refactor/home-screen-localization
  app/src/main/java/com/karrar/movieapp/domain/enums/HomeItemsType.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/ActorMoviesAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/ActorViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/adapters/MovieAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/allMedia/AllMovieFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeItem.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/home/adapter/HomeAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/home/homeUiState/HomeItemsType.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/MovieDetailsViewModel.kt
  app/src/main/res/layout/fragment_actor_details.xml
  app/src/main/res/layout/item_airing_today.xml
  app/src/main/res/layout/item_movie.xml
  app/src/main/res/layout/item_movie_actor.xml
  app/src/main/res/layout/item_needmoretowatch.xml
  app/src/main/res/layout/item_similar_movie.xml
  app/src/main/res/layout/item_tvshow.xml
  app/src/main/res/layout/item_whatshouldwatch.xml
  app/src/main/res/layout/list_home_collections.xml
  app/src/main/res/layout/list_movie.xml
  app/src/main/res/layout/list_tv_shows.xml
  app/src/main/res/layout/list_tvshow.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#111 Refactor: Update UI elements in login ,search and match screens
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_match_screen.xml
Labels: bug

#99 Refactor: Actor gallery section
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/ActorDetailsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/ActorDetailsUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/ActorViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/actorGallery/ActorGalleryFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/actorGallery/ActorImageAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/actorGallery/GalleryItem.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/layout/fragment_actor_details.xml
  app/src/main/res/layout/fragment_actor_gallery.xml
  app/src/main/res/layout/item_actor_image.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_actor_details_scene.xml
Labels: feature

#127 Feature/featured collections
  app/src/main/java/com/karrar/movieapp/ui/actorDetails/ActorDetailsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/allMedia/AllMovieFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/allMedia/AllMovieViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/home/homeUiState/HomeUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/home/homeUiState/HomeUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/home/homeUiState/IdType.kt
  app/src/main/res/layout/featured_item_card.xml
  app/src/main/res/navigation/movie_navigation.xml
Labels: feature

#124 refactor change language and change theme
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/karrar/movieapp/MovieApplication.kt
  app/src/main/java/com/karrar/movieapp/data/LanguageInterceptor.kt
  app/src/main/java/com/karrar/movieapp/data/local/AppConfiguration.kt
  app/src/main/java/com/karrar/movieapp/data/repository/AccountRepository.kt
  app/src/main/java/com/karrar/movieapp/data/repository/AccountRepositoryImp.kt
  app/src/main/java/com/karrar/movieapp/data/repository/SettingsRepository.kt
  app/src/main/java/com/karrar/movieapp/data/repository/SettingsRepositoryImp.kt
  app/src/main/java/com/karrar/movieapp/di/NetworkModule.kt
  app/src/main/java/com/karrar/movieapp/di/SettingsModule.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/setting/GetDarkModeUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/setting/GetLanguageUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/setting/SaveDarkModeUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/setting/SaveLanguageUseCase.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/language/LanguageBottomSheetDialog.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/language/LanguageViewModel.kt
  app/src/main/java/com/karrar/movieapp/utilities/LocaleManager.kt
  app/src/main/res/layout/bottom_sheet_language.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/local_configs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#131 Refactor/enhancement explore screen
  app/src/main/java/com/karrar/movieapp/data/util/ResourceProviderImp.kt
  app/src/main/java/com/karrar/movieapp/di/ResourceModule.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/GetGenreListUseCase.kt
  app/src/main/java/com/karrar/movieapp/domain/util/ResourceProvider.kt
  app/src/main/java/com/karrar/movieapp/ui/explore/ExploringFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/explore/ExploringViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/explore/exploreUIState/ExploreUIState.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/drawable/media_place_holder.xml
  app/src/main/res/layout/fragment_exploring.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/media_toggle_view.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
